@startuml
'https://plantuml.com/sequence-diagram

skinparam classAttributeIconSize 0
skinparam classFontStyle Bold
skinparam style strictuml
hide empty members

package inscryption
{
    class Joueur
    {
        + m_nbCartes: Integer
        + m_cartes: Carte
    }

    package Carte
    {
        abstract class CarteAnimaux <<abstract>>
        {
            - m_nom: String
            - m_ptAttaque: Integer
            - m_pDV: Integer
            - m_nbGouttesSang: Integer
            - m_nbOs: Integer
            - m_estvolant: Boolean
            + attaquer()
        }

        abstract class CarteObstacle <<abstract>>
        {
            - m_nom: String
            - m_pDV: Integer
        }

        class Rocher extends CarteObstacle
        {
            <<create>>Rocher(nom: String, pdv: Integer)
        }

        class Sapin extends CarteObstacle
        {
            <<create>>Sapin(nom: String, pdv: Integer)
        }

        class Chat extends CarteAnimaux
        {
            <<create>>Chat(ptAttaque: Integer, pDV: Integer, nbGouttesSang: Integer, nbOs: Integer, vole: Boolean)
        }

        class Grizzly extends CarteAnimaux
        {
            <<create>>Grizzly(ptAttaque: Integer, pDV: Integer, nbGouttesSang: Integer, nbOs: Integer, vole: Boolean)
        }

        class Coyote extends CarteAnimaux
        {
            <<create>>Coyote(ptAttaque: Integer, pDV: Integer, nbGouttesSang: Integer, nbOs: Integer, vole: Boolean)
        }

        class Moineau extends CarteAnimaux
        {
            <<create>>Moineau(ptAttaque: Integer, pDV: Integer, nbGouttesSang: Integer, nbOs: Integer, vole: Boolean)
        }

        class Corbeau extends CarteAnimaux
        {
            <<create>>Corbeau(ptAttaque: Integer, pDV: Integer, nbGouttesSang: Integer, nbOs: Integer, vole: Boolean)
        }

        class Ecureuil extends CarteAnimaux
        {
             <<create>>Ecureuil(ptAttaque: Integer, pDV: Integer, nbGouttesSang: Integer, nbOs: Integer, vole: Boolean)
        }

        class Hermine extends CarteAnimaux
        {
             <<create>>Hermine(ptAttaque: Integer, pDV: Integer, nbGouttesSang: Integer, nbOs: Integer, vole: Boolean)
        }

        class Louveteau extends CarteAnimaux
        {
             <<create>>Louveteau(ptAttaque: Integer, pDV: Integer, nbGouttesSang: Integer, nbOs: Integer, vole: Boolean)
        }

        class Loup extends CarteAnimaux
        {
             <<create>>Loup(ptAttaque: Integer, pDV: Integer, nbGouttesSang: Integer, nbOs: Integer, vole: Boolean)
        }

        class Punaise extends CarteAnimaux
        {
             <<create>>Punaise(ptAttaque: Integer, pDV: Integer, nbGouttesSang: Integer, nbOs: Integer, vole: Boolean)
        }
    }
}
@enduml